In [1]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

connection = psycopg2.connect(
    host="localhost",
    database="zeppelin",
    user="isaiahtp",
    password=""
)
uri = "postgresql+psycopg2://isaiahtp@localhost:5432/zeppelin?application_name=PyCharm"
cursor = connection.cursor()
engine = create_engine(uri, echo=True)

In [18]:
test = pd.read_parquet("ticks_test.parquet")
test = test.applymap(lambda x: str(x) if isinstance(x, pd.Timedelta) else x)
#test.reset_index(inplace=True, drop=False, names='Symbol')
test.applymap(type)

,Symbol,Start,End,Duration,Exposure Time [%],Equity Final [$],Equity Peak [$],Return [%],Buy & Hold Return [%],Return (Ann.) [%],...,Worst Trade [%],Avg. Trade [%],Max. Trade Duration,Avg. Trade Duration,Profit Factor,Expectancy [%],SQN,_strategy,_equity_curve,_trades
0,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,...,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'str'>
1,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,...,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'str'>
2,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,...,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'str'>
3,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,...,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'str'>
4,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,...,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'str'>
5,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,...,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'str'>
6,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,...,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'str'>
7,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,...,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'decimal.Decimal'>,<class 'str'>,<class 'str'>,<class 'str'>

In [2]:
from sqlalchemy import types

In [6]:
column_dtypes = {
    'Symbol': types.VARCHAR(length=5),
    'Start': types.Date,
    'Ended': types.Date,
    'Duration': types.Interval,
    'Exposure Time [%]': types.Numeric(18, 2),
    'Equity Final [$]': types.Numeric(18, 2),
    'Equity Peak [$]': types.Numeric(18, 2),
    'Return [%]': types.Numeric(18, 2),
    'Buy & Hold Return [%]': types.Numeric(18, 6),
    'Return (Ann.) [%]': types.Numeric(18, 6),
    'Volatility (Ann.) [%]': types.Numeric(18, 6),
    'Sharpe Ratio': types.Numeric(18, 6),
    'Sortino Ratio': types.Numeric(18, 6),
    'Calmar Ratio': types.Numeric(18, 6),
    'Max. Drawdown [%]': types.Numeric(18, 6),
    'Avg. Drawdown [%]': types.Numeric(18, 6),
    'Max. Drawdown Duration': types.Interval,
    'Avg. Drawdown Duration': types.Interval,
    '# Trades': types.Integer,
    'Win Rate [%]': types.VARCHAR(length=32),
    #'Win Rate [%]': types.Numeric(18, 2),
    'Best Trade [%]': types.Numeric(18, 6),
    'Worst Trade [%]': types.Numeric(18, 6),
    'Avg. Trade [%]': types.Numeric(18, 6),
    'Max. Trade Duration': types.Interval,
    'Avg. Trade Duration': types.Interval,
    'Profit Factor': types.Numeric(18, 6),
    'Expectancy [%]': types.Numeric(18, 6),
    'SQN': types.Numeric(18, 6),
    '_strategy': types.Text,
    '_equity_curve': types.Text,
    '_trades': types.Text
}
#cols = list(column_dtypes.keys())
test.to_sql('bt_stats', con=engine, index=False, if_exists='replace', dtype=column_dtypes)

8

In [14]:
%store -r aapl

/Users/isaiahtp/Desktop/Zeppelin/z-algo/zeppelin/lib/python3.11/site-packages/backtesting/_plotting.py:50: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support (e.g. PyCharm, Spyder IDE). Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '

In [28]:
aapl.iloc[:,-3:].applymap(type)
#["_strategy"] = aapl["_strategy"].astype(str)

,_strategy,_equity_curve,_trades
AAPL,<class 'str'>,<class 'pandas.core.frame.DataFrame'>,<class 'pandas.core.frame.DataFrame'>

In [36]:
aapl["_equity_curve"]

                                          _equity_curve
AAPL                             Equity  DrawdownPct...

In [21]:
aapl.to_sql('aapl', con=engine, index=False, if_exists='replace', dtype=column_dtypes)

/var/folders/jn/6_8h_cj14rv1f9p8_j_fhxfh0000gn/T/ipykernel_11417/3579901593.py:1: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  aapl.to_sql('aapl', con=engine, index=False, if_exists='replace', dtype=column_dtypes)

ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'DataFrame'
[SQL: INSERT INTO aapl ("('Start',)", "('End',)", "('Duration',)", "('Exposure Time [%%]',)", "('Equity Final [$]',)", "('Equity Peak [$]',)", "('Return [%%]',)", "('Buy & Hold Return [%%]',)", "('Return (Ann.) [%%]',)", "('Volatility (Ann.) [%%]',)", "('Sharpe Ratio',)", "('Sortino Ratio',)", "('Calmar Ratio',)", "('Max. Drawdown [%%]',)", "('Avg. Drawdown [%%]',)", "('Max. Drawdown Duration',)", "('Avg. Drawdown Duration',)", "('# Trades',)", "('Win Rate [%%]',)", "('Best Trade [%%]',)", "('Worst Trade [%%]',)", "('Avg. Trade [%%]',)", "('Max. Trade Duration',)", "('Avg. Trade Duration',)", "('Profit Factor',)", "('Expectancy [%%]',)", "('SQN',)", "('_strategy',)", "('_equity_curve',)", "('_trades',)") VALUES (%(A'Start',Z)s, %(A'End',Z)s, %(A'Duration',Z)s, %(A'Exposure_Time__P_',Z)s, %(A'Equity_Final__$_',Z)s, %(A'Equity_Peak__$_',Z)s, %(A'Return__P_',Z)s, %(A'Buy_&_Hold_Return__P_',Z)s, %(A'Return_AAnn_Z__P_',Z)s, %(A'Volatility_AAnn_Z__P_',Z)s, %(A'Sharpe_Ratio',Z)s, %(A'Sortino_Ratio',Z)s, %(A'Calmar_Ratio',Z)s, %(A'Max__Drawdown__P_',Z)s, %(A'Avg__Drawdown__P_',Z)s, %(A'Max__Drawdown_Duration',Z)s, %(A'Avg__Drawdown_Duration',Z)s, %(A'#_Trades',Z)s, %(A'Win_Rate__P_',Z)s, %(A'Best_Trade__P_',Z)s, %(A'Worst_Trade__P_',Z)s, %(A'Avg__Trade__P_',Z)s, %(A'Max__Trade_Duration',Z)s, %(A'Avg__Trade_Duration',Z)s, %(A'Profit_Factor',Z)s, %(A'Expectancy__P_',Z)s, %(A'SQN',Z)s, %(A'_strategy',Z)s, %(A'_equity_curve',Z)s, %(A'_trades',Z)s)]
[parameters: {"A'Start',Z": datetime.datetime(2024, 2, 5, 9, 30), "A'End',Z": datetime.datetime(2024, 2, 16, 14, 29, 55), "A'Duration',Z": 968395000000000, "A'Exposure_Time__P_',Z": 81.95975503062117, "A'Equity_Final__$_',Z": 97967.07924999994, "A'Equity_Peak__$_',Z": 100159.08395999999, "A'Return__P_',Z": -2.032920750000063, "A'Buy_&_Hold_Return__P_',Z": -2.4865555614717088, "A'Return_AAnn_Z__P_',Z": -42.73926167860023, "A'Volatility_AAnn_Z__P_',Z": 3.215666769892113, "A'Sharpe_Ratio',Z": 0.0, "A'Sortino_Ratio',Z": 0.0, "A'Calmar_Ratio',Z": 0.0, "A'Max__Drawdown__P_',Z": -3.094505548031834, "A'Avg__Drawdown__P_',Z": -0.13712362992588173, "A'Max__Drawdown_Duration',Z": 795595000000000, "A'Avg__Drawdown_Duration',Z": 29664000000000, "A'#_Trades',Z": 1619, "A'Win_Rate__P_',Z": 0.670166769610871, "A'Best_Trade__P_',Z": 0.16408713213122983, "A'Worst_Trade__P_',Z": -4.266259289936336, "A'Avg__Trade__P_',Z": -0.6755735624757508, "A'Max__Trade_Duration',Z": 795590000000000, "A'Avg__Trade_Duration',Z": 116926000000000, "A'Profit_Factor',Z": 0.09053276809511006, "A'Expectancy__P_',Z": -0.6690781454740996, "A'SQN',Z": -23.745173720481784, "A'_strategy',Z": 'Zeppelin', "A'_equity_curve',Z":                            Equity  DrawdownPct DrawdownDuration
Date
2024-02-05 09:30:00  1 ... (557 characters truncated) ... 4-02-16 14:29:50   97962.11555     0.021935              NaT
2024-02-16 14:29:55   97967.07925     0.021885  9 days 04:59:55

[45720 rows x 3 columns], "A'_trades',Z":       Size  EntryBar  ExitBar  EntryPrice  ExitPrice      PnL  ReturnPct  \
0        1       182      244   186.24174  186.41758  0.17584   0.000944   ... (1394 characters truncated) ... 617 2024-02-07 09:30:05 2024-02-16 14:29:55 9 days 04:59:50
1618 2024-02-07 09:30:05 2024-02-16 14:29:55 9 days 04:59:50

[1619 rows x 10 columns]}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [19]:
type(1.0-0.1)

float

In [15]:
aapl.equals

,Start,End,Duration,Exposure Time [%],Equity Final [$],Equity Peak [$],Return [%],Buy & Hold Return [%],Return (Ann.) [%],Volatility (Ann.) [%],...,Worst Trade [%],Avg. Trade [%],Max. Trade Duration,Avg. Trade Duration,Profit Factor,Expectancy [%],SQN,_strategy,_equity_curve,_trades
AAPL,2024-02-05 09:30:00,2024-02-16 14:29:55,11 days 04:59:55,81.959755,97967.07925,100159.08396,-2.032921,-2.486556,-42.739262,3.215667,...,-4.266259,-0.675574,9 days 04:59:50,1 days 08:28:46,0.090533,-0.669078,-23.745174,Zeppelin,Equity DrawdownPct...,Size EntryBar ExitBar EntryPrice Exi...

In [9]:
query = "SELECT 'Symbol' from bt_stats;"
query2 = "SELECT * from smallticks;"
cursor.description

(Column(name='Symbol', type_code=1043),
 Column(name='Start', type_code=1082),
 Column(name='End', type_code=25),
 Column(name='Duration', type_code=1186),
 Column(name='Exposure Time [%]', type_code=1700),
 Column(name='Equity Final [$]', type_code=1700),
 Column(name='Equity Peak [$]', type_code=1700),
 Column(name='Return [%]', type_code=1700),
 Column(name='Buy & Hold Return [%]', type_code=1700),
 Column(name='Return (Ann.) [%]', type_code=1700),
 Column(name='Return Diff. [%]', type_code=25),
 Column(name='Volatility (Ann.) [%]', type_code=1700),
 Column(name='Sharpe Ratio', type_code=1700),
 Column(name='Sortino Ratio', type_code=1700),
 Column(name='Calmar Ratio', type_code=1700),
 Column(name='Max. Drawdown [%]', type_code=1700),
 Column(name='Avg. Drawdown [%]', type_code=1700),
 Column(name='Max. Drawdown Duration', type_code=1186),
 Column(name='Avg. Drawdown Duration', type_code=1186),
 Column(name='# Trades', type_code=23),
 Column(name='Win Rate [%]', type_code=1043),
 Column(name='Best Trade [%]', type_code=1700),
 Column(name='Worst Trade [%]', type_code=1700),
 Column(name='Avg. Trade [%]', type_code=1700),
 Column(name='Max. Trade Duration', type_code=1186),
 Column(name='Avg. Trade Duration', type_code=1186),
 Column(name='Profit Factor', type_code=1700),
 Column(name='Expectancy [%]', type_code=1700),
 Column(name='SQN', type_code=1700),
 Column(name='_strategy', type_code=25),
 Column(name='_equity_curve', type_code=25),
 Column(name='_trades', type_code=25))

NameError: name 'bt_stats' is not defined

In [10]:
try:
    cursor.execute("SELECT * from bt_stats;")
    results = cursor.fetchall()
    print(results)
except Exception as e:
    print(f"Error executing query: {e}")
    connection.rollback()

[('AMD', datetime.date(2024, 1, 5), '2024-02-16 15:59:55', datetime.timedelta(days=42, seconds=26980), Decimal('93.03'), Decimal('106842.08'), Decimal('111176.63'), Decimal('6.84'), Decimal('28.481668'), Decimal('68.608899'), '-21.6395883922691365', Decimal('59.551675'), Decimal('1.151378'), Decimal('3.106618'), Decimal('6.852344'), Decimal('-10.012471'), Decimal('-0.109197'), datetime.timedelta(days=21, seconds=18195), datetime.timedelta(seconds=6748), 15862, '15239 / 15862', Decimal('2.142243'), Decimal('-5.966784'), Decimal('0.286703'), datetime.timedelta(days=22, seconds=23085), datetime.timedelta(days=1, seconds=12301), Decimal('2.865182'), Decimal('0.290785'), Decimal('34.049464'), 'Zeppelin', '                           Equity  DrawdownPct DrawdownDuration\n2024-01-05 08:30:15  100000.00000     0.000000              NaT\n2024-01-05 08:30:20  100000.00000     0.000000              NaT\n2024-01-05 08:30:25  100000.00000     0.000000              NaT\n2024-01-05 08:30:30  100000.00000     0.000000              NaT\n2024-01-05 08:30:35  100000.00000     0.000000              NaT\n...                           ...          ...              ...\n2024-02-16 15:59:35  106872.77926     0.038712              NaT\n2024-02-16 15:59:40  106872.77926     0.038712              NaT\n2024-02-16 15:59:45  106842.07926     0.038988              NaT\n2024-02-16 15:59:50  106842.07926     0.038988              NaT\n2024-02-16 15:59:55  106842.07926     0.038988 21 days 05:03:15\n\n[150650 rows x 3 columns]', '       Size  EntryBar  ...            ExitTime         Duration\n0         1       378  ... 2024-01-05 09:19:00  0 days 00:17:15\n1         1       377  ... 2024-01-05 09:19:00  0 days 00:17:20\n2         1       376  ... 2024-01-05 09:19:00  0 days 00:17:25\n3         1       375  ... 2024-01-05 09:19:00  0 days 00:17:30\n4         1       374  ... 2024-01-05 09:19:00  0 days 00:17:35\n...     ...       ...  ...                 ...              ...\n15857     1     66123  ... 2024-02-16 15:59:55 22 days 06:24:20\n15858     1     66122  ... 2024-02-16 15:59:55 22 days 06:24:25\n15859     1     66121  ... 2024-02-16 15:59:55 22 days 06:24:30\n15860     1     66119  ... 2024-02-16 15:59:55 22 days 06:24:40\n15861     1     66118  ... 2024-02-16 15:59:55 22 days 06:24:45\n\n[15862 rows x 10 columns]'), ('AMGN', datetime.date(2024, 1, 5), '2024-02-16 15:59:55', datetime.timedelta(days=42, seconds=23205), Decimal('91.52'), Decimal('90345.94'), Decimal('104251.34'), Decimal('-9.65'), Decimal('-5.878055'), Decimal('-57.378133'), '-3.7760074996415680', Decimal('10.472806'), Decimal('0.000000'), Decimal('0.000000'), Decimal('0.000000'), Decimal('-13.341391'), Decimal('-0.684811'), datetime.timedelta(days=13, seconds=695), datetime.timedelta(seconds=85305), 2936, '2616 / 2936', Decimal('1.676028'), Decimal('-13.994682'), Decimal('-1.092565'), datetime.timedelta(days=13, seconds=3430), datetime.timedelta(days=3, seconds=64320), Decimal('0.320115'), Decimal('-0.989635'), Decimal('-12.541964'), 'Zeppelin', '                           Equity  DrawdownPct DrawdownDuration\n2024-01-05 09:33:10  100000.00000     0.000000              NaT\n2024-01-05 09:33:15  100000.00000     0.000000              NaT\n2024-01-05 09:33:20  100000.00000     0.000000              NaT\n2024-01-05 09:33:25  100000.00000     0.000000              NaT\n2024-01-05 09:33:30  100000.00000     0.000000              NaT\n...                           ...          ...              ...\n2024-02-16 15:59:35   90345.93724     0.133383              NaT\n2024-02-16 15:59:40   90345.93724     0.133383              NaT\n2024-02-16 15:59:45   90345.93724     0.133383              NaT\n2024-02-16 15:59:50   90345.93724     0.133383              NaT\n2024-02-16 15:59:55   90345.93724     0.133383 11 days 06:03:50\n\n[139210 rows x 3 columns]', '      Size  EntryBar  ...            ExitTime         Duration\n0        1      4801  ... 2024-01-08 10:22:10  0 days 00:38:50\n1        1      9325  ... 2024-01-09 09:35:35  0 days 00:04:05\n2        1      9324  ... 2024-01-09 09:35:35  0 days 00:04:10\n3        1      9323  ... 2024-01-09 09:35:35  0 days 00:04:15\n4        1      9322  ... 2024-01-09 09:35:35  0 days 00:04:20\n...    ...       ...  ...                 ...              ...\n2931     1     92839  ... 2024-02-16 15:59:55 11 days 06:05:45\n2932     1     92838  ... 2024-02-16 15:59:55 11 days 06:05:50\n2933     1     92837  ... 2024-02-16 15:59:55 11 days 06:05:55\n2934     1     92836  ... 2024-02-16 15:59:55 11 days 06:06:00\n2935     1     92835  ... 2024-02-16 15:59:55 11 days 06:06:05\n\n[2936 rows x 10 columns]'), ('JPM', datetime.date(2024, 1, 5), '2024-02-16 15:59:55', datetime.timedelta(days=42, seconds=23395), Decimal('91.83'), Decimal('104399.53'), Decimal('104643.94'), Decimal('4.40'), Decimal('4.232404'), Decimal('43.571350'), '0.1671267142284660', Decimal('16.878309'), Decimal('2.578988'), Decimal('5.949567'), Decimal('10.390782'), Decimal('-4.193269'), Decimal('-0.072612'), datetime.timedelta(days=14, seconds=86145), datetime.timedelta(seconds=14885), 6242, '5748 / 6242', Decimal('2.175479'), Decimal('-0.731958'), Decimal('0.407603'), datetime.timedelta(days=18, seconds=86275), datetime.timedelta(days=2, seconds=85182), Decimal('19.983998'), Decimal('0.409111'), Decimal('58.964404'), 'Zeppelin', '                           Equity  DrawdownPct DrawdownDuration\n2024-01-05 09:30:00  100000.00000     0.000000              NaT\n2024-01-05 09:30:05  100000.00000     0.000000              NaT\n2024-01-05 09:30:10  100000.00000     0.000000              NaT\n2024-01-05 09:30:15  100000.00000     0.000000              NaT\n2024-01-05 09:30:20  100000.00000     0.000000              NaT\n...                           ...          ...              ...\n2024-02-16 15:59:35  104422.85051     0.002113              NaT\n2024-02-16 15:59:40  104399.53051     0.002336              NaT\n2024-02-16 15:59:45  104393.70051     0.002391              NaT\n2024-02-16 15:59:50  104393.70051     0.002391              NaT\n2024-02-16 15:59:55  104399.53051     0.002336  0 days 05:44:15\n\n[140395 rows x 3 columns]', '      Size  EntryBar  ...            ExitTime        Duration\n0        1      9803  ... 2024-01-09 11:35:50 0 days 01:28:55\n1        1      9802  ... 2024-01-09 11:35:50 0 days 01:29:00\n2        1      9805  ... 2024-01-09 11:35:55 0 days 01:28:50\n3        1      9804  ... 2024-01-09 11:35:55 0 days 01:28:55\n4        1      9810  ... 2024-01-09 11:36:20 0 days 01:28:50\n...    ...       ...  ...                 ...             ...\n6237     1    135720  ... 2024-02-16 15:59:55 0 days 06:29:30\n6238     1    135719  ... 2024-02-16 15:59:55 0 days 06:29:35\n6239     1    135718  ... 2024-02-16 15:59:55 0 days 06:29:40\n6240     1    135717  ... 2024-02-16 15:59:55 0 days 06:29:45\n6241     1    135716  ... 2024-02-16 15:59:55 0 days 06:29:50\n\n[6242 rows x 10 columns]'), ('LYG', datetime.date(2024, 1, 5), '2024-02-16 15:59:55', datetime.timedelta(days=42, seconds=23395), Decimal('98.90'), Decimal('99730.96'), Decimal('100002.88'), Decimal('-0.27'), Decimal('-9.915612'), Decimal('-2.184462'), '9.6465732263449625', Decimal('0.605262'), Decimal('0.000000'), Decimal('0.000000'), Decimal('0.000000'), Decimal('-0.396286'), Decimal('-0.202824'), datetime.timedelta(days=38, seconds=23395), datetime.timedelta(days=20, seconds=60065), 1285, '290 / 1285', Decimal('0.633805'), Decimal('-11.587613'), Decimal('-8.819748'), datetime.timedelta(days=38, seconds=23390), datetime.timedelta(days=30, seconds=26727), Decimal('0.010609'), Decimal('-8.692824'), Decimal('-63.255726'), 'Zeppelin', '                            Equity  DrawdownPct DrawdownDuration\n2024-01-05 09:30:00  100000.000000     0.000000              NaT\n2024-01-05 09:30:05  100000.000000     0.000000              NaT\n2024-01-05 09:30:10  100000.000000     0.000000              NaT\n2024-01-05 09:30:15  100000.000000     0.000000              NaT\n2024-01-05 09:30:20  100000.000000     0.000000              NaT\n...                            ...          ...              ...\n2024-02-16 15:59:35   99735.936412     0.002669              NaT\n2024-02-16 15:59:40   99735.936412     0.002669              NaT\n2024-02-16 15:59:45   99730.961412     0.002719              NaT\n2024-02-16 15:59:50   99730.961412     0.002719              NaT\n2024-02-16 15:59:55   99730.961412     0.002719 38 days 06:29:55\n\n[140400 rows x 3 columns]', '      Size  EntryBar  ...            ExitTime         Duration\n0        1       936  ... 2024-01-08 12:57:20  3 days 02:09:20\n1        1       935  ... 2024-01-08 12:57:20  3 days 02:09:25\n2        1       934  ... 2024-01-08 12:57:20  3 days 02:09:30\n3        1       933  ... 2024-01-08 12:57:20  3 days 02:09:35\n4        1       932  ... 2024-01-08 12:57:20  3 days 02:09:40\n...    ...       ...  ...                 ...              ...\n1280     1      9365  ... 2024-02-16 15:59:55 38 days 06:29:30\n1281     1      9364  ... 2024-02-16 15:59:55 38 days 06:29:35\n1282     1      9363  ... 2024-02-16 15:59:55 38 days 06:29:40\n1283     1      9362  ... 2024-02-16 15:59:55 38 days 06:29:45\n1284     1      9361  ... 2024-02-16 15:59:55 38 days 06:29:50\n\n[1285 rows x 10 columns]'), ('ORCL', datetime.date(2024, 1, 5), '2024-02-16 15:59:55', datetime.timedelta(days=42, seconds=23395), Decimal('94.48'), Decimal('100913.56'), Decimal('106390.35'), Decimal('0.91'), Decimal('8.355244'), Decimal('7.938382'), '-7.4416874130648661', Decimal('18.285175'), Decimal('0.431824'), Decimal('0.334641'), Decimal('1.536999'), Decimal('-5.164858'), Decimal('-0.081689'), datetime.timedelta(days=7, seconds=77930), datetime.timedelta(seconds=8106), 14607, '13700 / 14607', Decimal('1.026924'), Decimal('-5.690868'), Decimal('0.068470'), datetime.timedelta(days=11, seconds=11160), datetime.timedelta(days=1, seconds=43263), Decimal('1.243868'), Decimal('0.077817'), Decimal('4.812039'), 'Zeppelin', '                            Equity  DrawdownPct DrawdownDuration\n2024-01-05 09:30:00  100000.000000     0.000000              NaT\n2024-01-05 09:30:05  100000.000000     0.000000              NaT\n2024-01-05 09:30:10  100000.000000     0.000000              NaT\n2024-01-05 09:30:15  100000.000000     0.000000              NaT\n2024-01-05 09:30:20  100000.000000     0.000000              NaT\n...                            ...          ...              ...\n2024-02-16 15:59:35  100922.616525     0.051393              NaT\n2024-02-16 15:59:40  100931.676525     0.051308              NaT\n2024-02-16 15:59:45  100949.796525     0.051138              NaT\n2024-02-16 15:59:50  100913.556525     0.051478              NaT\n2024-02-16 15:59:55  100913.556525     0.051478  7 days 06:28:20\n\n[139861 rows x 3 columns]', '       Size  EntryBar  ...            ExitTime        Duration\n0         1      5498  ... 2024-01-08 11:59:20 0 days 01:21:10\n1         1      5497  ... 2024-01-08 11:59:20 0 days 01:21:15\n2         1      5484  ... 2024-01-08 11:59:20 0 days 01:22:20\n3         1      5483  ... 2024-01-08 11:59:20 0 days 01:22:25\n4         1      5307  ... 2024-01-08 11:59:20 0 days 01:37:05\n...     ...       ...  ...                 ...             ...\n14602     1    107242  ... 2024-02-16 15:59:55 8 days 06:27:30\n14603     1    107241  ... 2024-02-16 15:59:55 8 days 06:27:35\n14604     1    107240  ... 2024-02-16 15:59:55 8 days 06:27:40\n14605     1    107239  ... 2024-02-16 15:59:55 8 days 06:27:45\n14606     1    107238  ... 2024-02-16 15:59:55 8 days 06:27:50\n\n[14607 rows x 10 columns]'), ('QQQ', datetime.date(2024, 1, 5), '2024-02-16 15:59:55', datetime.timedelta(days=42, seconds=23395), Decimal('91.42'), Decimal('103198.97'), Decimal('105014.99'), Decimal('3.20'), Decimal('8.636088'), Decimal('30.278601'), '-5.4371172594807050', Decimal('17.332635'), Decimal('1.744467'), Decimal('3.011413'), Decimal('10.370378'), Decimal('-2.919720'), Decimal('-0.056923'), datetime.timedelta(days=8, seconds=84760), datetime.timedelta(seconds=6154), 2947, '2708 / 2947', Decimal('1.000372'), Decimal('-1.948847'), Decimal('0.262867'), datetime.timedelta(days=13, seconds=85240), datetime.timedelta(days=2, seconds=38907), Decimal('2.983356'), Decimal('0.264557'), Decimal('23.456120'), 'Zeppelin', '                            Equity  DrawdownPct DrawdownDuration\n2024-01-05 09:30:00  100000.000000     0.000000              NaT\n2024-01-05 09:30:05  100000.000000     0.000000              NaT\n2024-01-05 09:30:10  100000.000000     0.000000              NaT\n2024-01-05 09:30:15  100000.000000     0.000000              NaT\n2024-01-05 09:30:20  100000.000000     0.000000              NaT\n...                            ...          ...              ...\n2024-02-16 15:59:35  103220.481145     0.017088              NaT\n2024-02-16 15:59:40  103189.411145     0.017384              NaT\n2024-02-16 15:59:45  103184.631145     0.017429              NaT\n2024-02-16 15:59:50  103198.971145     0.017293              NaT\n2024-02-16 15:59:55  103198.971145     0.017293  4 days 04:21:50\n\n[140400 rows x 3 columns]', '      Size  EntryBar  ...            ExitTime        Duration\n0        1      5566  ... 2024-01-08 14:10:45 0 days 03:26:55\n1        1      5565  ... 2024-01-08 14:10:45 0 days 03:27:00\n2        1      5520  ... 2024-01-08 14:10:45 0 days 03:30:45\n3        1      5519  ... 2024-01-08 14:10:45 0 days 03:30:50\n4        1      5507  ... 2024-01-08 14:10:45 0 days 03:31:50\n...    ...       ...  ...                 ...             ...\n2942     1    117005  ... 2024-02-16 15:59:55 4 days 06:29:30\n2943     1    117004  ... 2024-02-16 15:59:55 4 days 06:29:35\n2944     1    117003  ... 2024-02-16 15:59:55 4 days 06:29:40\n2945     1    117002  ... 2024-02-16 15:59:55 4 days 06:29:45\n2946     1    117001  ... 2024-02-16 15:59:55 4 days 06:29:50\n\n[2947 rows x 10 columns]'), ('UL', datetime.date(2024, 1, 5), '2024-02-16 15:59:55', datetime.timedelta(days=42, seconds=23395), Decimal('92.92'), Decimal('102660.20'), Decimal('102969.45'), Decimal('2.66'), Decimal('4.257507'), Decimal('24.674556'), '-1.5973032536838730', Decimal('18.033685'), Decimal('1.365897'), Decimal('2.923121'), Decimal('8.747767'), Decimal('-2.820669'), Decimal('-0.235763'), datetime.timedelta(days=20, seconds=21835), datetime.timedelta(days=1, seconds=10717), 5991, '4527 / 5991', Decimal('3.199926'), Decimal('-1.251567'), Decimal('0.890012'), datetime.timedelta(days=25, seconds=3955), datetime.timedelta(days=7, seconds=72131), Decimal('7.014208'), Decimal('0.898970'), Decimal('51.221441'), 'Zeppelin', '                            Equity  DrawdownPct DrawdownDuration\n2024-01-05 09:30:00  100000.000000     0.000000              NaT\n2024-01-05 09:30:05  100000.000000     0.000000              NaT\n2024-01-05 09:30:10  100000.000000     0.000000              NaT\n2024-01-05 09:30:15  100000.000000     0.000000              NaT\n2024-01-05 09:30:20  100000.000000     0.000000              NaT\n...                            ...          ...              ...\n2024-02-16 15:59:35  102675.793945     0.002852              NaT\n2024-02-16 15:59:40  102675.793945     0.002852              NaT\n2024-02-16 15:59:45  102675.793945     0.002852              NaT\n2024-02-16 15:59:50  102660.203945     0.003003              NaT\n2024-02-16 15:59:55  102660.203945     0.003003  8 days 06:25:20\n\n[140400 rows x 3 columns]', '      Size  EntryBar  ...            ExitTime        Duration\n0        1     51481  ... 2024-01-23 09:32:20 0 days 00:02:15\n1        1     74881  ... 2024-01-31 09:30:00 0 days 23:59:55\n2        1     79967  ... 2024-02-01 15:59:50 1 days 05:55:55\n3        1     79966  ... 2024-02-01 15:59:50 1 days 05:56:00\n4        1     79965  ... 2024-02-01 15:59:50 1 days 05:56:05\n...    ...       ...  ...                 ...             ...\n5986     1    107645  ... 2024-02-16 15:59:55 8 days 06:29:30\n5987     1    107644  ... 2024-02-16 15:59:55 8 days 06:29:35\n5988     1    107643  ... 2024-02-16 15:59:55 8 days 06:29:40\n5989     1    107642  ... 2024-02-16 15:59:55 8 days 06:29:45\n5990     1    107641  ... 2024-02-16 15:59:55 8 days 06:29:50\n\n[5991 rows x 10 columns]'), ('V', datetime.date(2024, 1, 5), '2024-02-16 15:59:55', datetime.timedelta(days=42, seconds=23395), Decimal('90.58'), Decimal('102858.98'), Decimal('103770.01'), Decimal('2.86'), Decimal('6.790644'), Decimal('27.747707'), '-3.9316634667788767', Decimal('17.193629'), Decimal('1.611371'), Decimal('2.553485'), Decimal('10.892250'), Decimal('-2.547472'), Decimal('-0.095758'), datetime.timedelta(days=7, seconds=71880), datetime.timedelta(seconds=13726), 3805, '3434 / 3805', Decimal('0.725382'), Decimal('-1.087758'), Decimal('0.280386'), datetime.timedelta(days=16, seconds=23225), datetime.timedelta(days=3, seconds=34861), Decimal('4.565928'), Decimal('0.281077'), Decimal('45.049110'), 'Zeppelin', '                            Equity  DrawdownPct DrawdownDuration\n2024-01-05 09:30:00  100000.000000     0.000000              NaT\n2024-01-05 09:30:05  100000.000000     0.000000              NaT\n2024-01-05 09:30:10  100000.000000     0.000000              NaT\n2024-01-05 09:30:15  100000.000000     0.000000              NaT\n2024-01-05 09:30:20  100000.000000     0.000000              NaT\n...                            ...          ...              ...\n2024-02-16 15:59:35  102825.770705     0.009099              NaT\n2024-02-16 15:59:40  102818.390705     0.009171              NaT\n2024-02-16 15:59:45  102855.290705     0.008815              NaT\n2024-02-16 15:59:50  102858.980705     0.008779              NaT\n2024-02-16 15:59:55  102858.980705     0.008779  1 days 00:07:55\n\n[140400 rows x 3 columns]', '      Size  EntryBar  ...            ExitTime         Duration\n0        1      2729  ... 2024-01-05 13:30:15  0 days 00:12:50\n1        1      2728  ... 2024-01-05 13:30:15  0 days 00:12:55\n2        1      2715  ... 2024-01-05 13:30:15  0 days 00:14:00\n3        1      2727  ... 2024-01-05 13:30:55  0 days 00:13:40\n4        1      2726  ... 2024-01-05 13:30:55  0 days 00:13:45\n...    ...       ...  ...                 ...              ...\n3800     1     79599  ... 2024-02-16 15:59:55 16 days 06:26:40\n3801     1     79598  ... 2024-02-16 15:59:55 16 days 06:26:45\n3802     1     79596  ... 2024-02-16 15:59:55 16 days 06:26:55\n3803     1     79595  ... 2024-02-16 15:59:55 16 days 06:27:00\n3804     1     79594  ... 2024-02-16 15:59:55 16 days 06:27:05\n\n[3805 rows x 10 columns]')]

In [12]:
from datetime import datetime
from decimal import Decimal

In [21]:
pyth_dtypes = {
    'Symbol': str,
    'Start': datetime.date,
    'Ended': datetime.date,
    'Duration': pd.Timedelta,
    'Exposure Time [%]': Decimal,
    'Equity Final [$]': Decimal,
    'Equity Peak [$]': Decimal,
    'Return [%]': Decimal,
    'Buy & Hold Return [%]': Decimal,
    'Return (Ann.) [%]': Decimal,
    'Volatility (Ann.) [%]': Decimal,
    'Sharpe Ratio': Decimal,
    'Sortino Ratio': Decimal,
    'Calmar Ratio': Decimal,
    'Max. Drawdown [%]': Decimal,
    'Avg. Drawdown [%]': Decimal,
    'Max. Drawdown Duration': pd.Timedelta,
    'Avg. Drawdown Duration': pd.Timedelta,
    '# Trades': int,
    'Win Rate [%]': str,  # You can change this to Decimal if applicable
    'Best Trade [%]': Decimal,
    'Worst Trade [%]': Decimal,
    'Avg. Trade [%]': Decimal,
    'Max. Trade Duration': pd.Timedelta,
    'Avg. Trade Duration': pd.Timedelta,
    'Profit Factor': Decimal,
    'Expectancy [%]': Decimal,
    'SQN': Decimal,
    '_strategy': str,
    '_equity_curve': str,
    '_trades': str
}

In [22]:
woah = pd.read_sql("bt_stats", engine, parse_dates=True, dtype=pyth_dtypes)
woah
woah.applymap(type)

,Symbol,Start,End,Duration,Exposure Time [%],Equity Final [$],Equity Peak [$],Return [%],Buy & Hold Return [%],Return (Ann.) [%],...,Worst Trade [%],Avg. Trade [%],Max. Trade Duration,Avg. Trade Duration,Profit Factor,Expectancy [%],SQN,_strategy,_equity_curve,_trades
0,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'str'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'str'>
1,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'str'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'str'>
2,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'str'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'str'>
3,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'str'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'str'>
4,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'str'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'str'>
5,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'str'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'str'>
6,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'str'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'str'>
7,<class 'str'>,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'str'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,<class 'float'>,...,<class 'float'>,<class 'float'>,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'pandas._libs.tslibs.timedeltas.Timedel...,<class 'float'>,<class 'float'>,<class 'float'>,<class 'str'>,<class 'str'>,<class 'str'>

In [ ]:
cursor.description
cursor.fetchall()
cursor.description
cursor.execute("SELECT * FROM pg_indexes;")
cursor.fetchall()

In [0]:

# Fetch the result into a Pandas DataFrame
df = pd.DataFrame(result.fetchall(), columns=result.keys())
# Print or use the DataFrame as needed
print(df)
cursor.close()
connection.close()
cursor
connection.rollback()

In [3]:
connection.rollback()